---
- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Add /etc/hosts details
  become: yes
  blockinfile:
    path: /etc/hosts
    marker: ''
    block: |
      {{ item.ip }} {{ item.name }}
  loop:
    - { name: esd1, ip: 192.168.28.71 }
    - { name: esd2, ip: 192.168.28.72 }
    - { name: esd3, ip: 192.168.28.73 }
    - { name: esm1, ip: 192.168.28.74 }
    - { name: esm2, ip: 192.168.28.75 }
    - { name: esm3, ip: 192.168.28.76 }

